POST http://localhost:8080/login
Content-Type: application/json

{
    "username": "user1",
    "password": "password1"
}
###

GET http://localhost:8080/systemInfo

###

DELETE  http://localhost:8080/users?id=asd23234
Authorization: mf9oxjfeugb

###
GET http://localhost:8080/users?id=asd23234
Authorization: dzrurgklde8

###

GET http://localhost:8080/users?name=aro
Authorization: dzrurgklde8

###
PUT http://localhost:8080/users
Authorization: dzrurgklde8
Content-Type: application/json

{
  "age": 45,
  "email": "some@otheremail.com",
  "name": "barosanu",
  "workingPosition": 3
}